// Curate the 24 gallery pieces from the pixel-audit results: passing seeds only, highest quality first, greedily
// covering the trait space (every horizon ×6, every inclusion, every form, every light class, both rare palettes …).
//
//   npm run audit:pixels          # writes docs/audit/pixels-main.json
//   npx tsx scripts/pick-gallery.ts [--exclude i,j,k]   # writes src/data/gallery.ts ; then LOOK at it and swap by hand if needed
//
// Each pick is an (audit index i → seed, horizon i%4, sky rehearsal(i)) triple that was rendered and measured in the audit.

import { readFileSync, writeFileSync } from 'node:fs';
import { rehearsalSky, seedFromText } from '../src/art/index.ts';

const argv = process.argv.slice(2);
const excl = new Set((argv[argv.indexOf('--exclude') + 1] ?? '').split(',').filter(Boolean).map(Number));
type Row = { i: number; seed: string; horizon: number; title: string; tier: string; traits: Record<string, string>; q: number; why: string[]; m: { colorfulness: number } };
const rows: Row[] = JSON.parse(readFileSync('docs/audit/pixels-main.json', 'utf8'));
const pool = rows.filter((r) => !r.why.length && !excl.has(r.i));

const want: Record<string, string[]> = {
  Inclusion: ['Kintsugi Seam', 'Twin Bloom', 'Eclipse', 'Aurora Veil', 'Halo Rings', 'Comet', 'Full Spectrum'],
  Form: ['Lance', 'Teardrop', 'Shard', 'Ribbon', 'Coronet'],
  Light: ['Lamp', 'Radiant', 'Blazing', 'Nova'],
  Growth: ['Silk', 'Root', 'Coral', 'Reed', 'Storm'],
  Glass: ['Clear', 'Stained', 'Frosted', 'Prismatic'],
  Dust: ['Sparse', 'Drifting', 'Snowfall', 'Starfall'],
  Interface: ['Level', 'Leaning', 'Fan', 'Folded'],
  Palette: ['Aurora Prism', 'Blackglass', 'Verdigris Night', 'Ember Reef', 'Cobalt Vesper', 'Rose Quartz Dusk', 'Saffron Tide', 'Glacier Wick', 'Orchid Static', 'Moss Cathedral', 'Oxide Sun', 'Ink Wisteria', 'Anemone Drift', 'Sulphur Lamp'],
  Sheets: ['3', '4', '5', '6', '7'],
};
const have = new Set<string>();
const picks: Row[] = [];
const perHorizon = [0, 0, 0, 0];
const perPalette = new Map<string, number>();

while (picks.length < 24) {
  let best: Row | null = null, bestScore = -Infinity;
  for (const r of pool) {
    if (picks.includes(r) || perHorizon[r.horizon]! >= 6) continue;
    if ((perPalette.get(r.traits.Palette!) ?? 0) >= 2) continue;
    let gain = 0;
    for (const [k, vals] of Object.entries(want)) { const v = r.traits[k]; if (v && vals.includes(v) && !have.has(k + '=' + v)) gain += k === 'Inclusion' || k === 'Palette' ? 2.4 : 1; }
    const score = gain * 1.0 + r.q * 4;
    if (score > bestScore) { bestScore = score; best = r; }
  }
  if (!best) break;
  picks.push(best);
  perHorizon[best.horizon]!++;
  perPalette.set(best.traits.Palette!, (perPalette.get(best.traits.Palette!) ?? 0) + 1);
  for (const [k, vals] of Object.entries(want)) { const v = best.traits[k]; if (v && vals.includes(v)) have.add(k + '=' + v); }
}

// Deterministic display order: interleave horizons so neighbours differ.
picks.sort((a, b) => (a.horizon - b.horizon) || (b.q - a.q));
const byH = [0, 1, 2, 3].map((h) => picks.filter((p) => p.horizon === h));
const order: Row[] = [];
for (let k = 0; order.length < picks.length; k++) for (const list of byH) if (list[k]) order.push(list[k]!);

const ids = new Set<number>();
const entries = order.map((r) => {
  let no = 1 + (parseInt(seedFromText('no' + r.seed).slice(0, 8), 16) % 512);
  while (ids.has(no)) no = (no % 512) + 1;
  ids.add(no);
  return { no, seed: r.seed, horizon: r.horizon, sky: rehearsalSky(r.i), i: r.i, title: r.title, traits: r.traits };
});

const missing = Object.entries(want).flatMap(([k, vals]) => vals.filter((v) => !have.has(k + '=' + v)).map((v) => `${k}=${v}`));
const src = `// The 24 curated pieces — generated by scripts/pick-gallery.ts from the pixel audit (docs/audit/pixels-main.json).
// Every entry is a (seed, horizon, sky) triple that was rendered and passed the quality gates. Hand-swap freely; keep the shape.
import type { PieceEntry } from './types.ts';

export type GalleryEntry = PieceEntry;

export const GALLERY: GalleryEntry[] = [
${entries.map((e) => `  { no: ${e.no}, seed: '${e.seed}', horizon: ${e.horizon}, sky: '${rehearsalSky(e.i)}' }, // #${e.i} ${e.title} · ${e.traits.Palette} · ${e.traits.Inclusion}`).join('\n')}
];
`;
writeFileSync('src/data/gallery.ts', src);
writeFileSync('src/data/types.ts', `export interface PieceEntry {
  /** token-style number shown as "No. 0037" (illustrative — the gallery is a rehearsal set) */
  no: number;
  seed: string;
  /** the horizon this piece was turned toward */
  horizon: 0 | 1 | 2 | 3;
  /** the (rehearsal) sky used for its bloom */
  sky: string;
}
`);
console.log(`picked ${entries.length}; horizons ${perHorizon}; uncovered: ${missing.join(', ') || 'none'}`);
for (const e of entries) console.log(`  #${String(e.i).padStart(4)} ${e.title.padEnd(22)} H${e.horizon}  ${e.traits.Palette} · ${e.traits.Form} · ${e.traits.Light} · ${e.traits.Inclusion}`);
